name: ".reusable-build"

on:
  workflow_call:
    inputs:
      HOST_USER_LOGIN:
        description: "Host user login"
        required: true
        type: "string"
    secrets:
      HOST_USER_PASSWORD:
        description: "Host user password"
        required: true
      HOST_CF_TUNNEL_TOKEN:
        description: "Cloudflare tunnel token"
        required: true
    outputs:
      ARTIFACT_NAME:
        description: "The name of the artifact produced"
        value: "${{ jobs.build.outputs.artifact_name }}"
      ARTIFACT_PATH:
        description: "The path of the artifact produced"
        value: "${{ jobs.build.outputs.artifact_path }}"

jobs:
  build:
    name: "Reusable Build"
    runs-on: [ "ubuntu-24.04" ]
    outputs:
      ARTIFACT_NAME: ${{ steps.resolve-artifact-name.outputs.ARTIFACT_NAME }}
      ARTIFACT_PATH: ${{ steps.resolve-artifact-path.outputs.ARTIFACT_PATH }}
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Build hosts.ini"
        env:
          HOST_USER_LOGIN: "${{ inputs.HOST_USER_LOGIN }}"
          HOST_USER_PASSWORD: "${{ secrets.HOST_USER_PASSWORD }}"
          HOST_CF_TUNNEL_TOKEN: "${{ secrets.HOST_CF_TUNNEL_TOKEN }}"
        run: |
          if [ -z "${HOST_USER_LOGIN}" ]; then
            echo "Error: HOST_USER_LOGIN is empty"
            exit 1
          fi
          if [ -z "${HOST_USER_PASSWORD}" ]; then
            echo "Error: HOST_USER_PASSWORD is empty"
            exit 1
          fi
          if [ -z "${HOST_CF_TUNNEL_TOKEN}" ]; then
            echo "Error: HOST_CF_TUNNEL_TOKEN is empty"
            exit 1
          fi
          envsubst < inventory/hosts.ini.template > inventory/hosts.ini
      - name: "Resolve artifact name"
        id: resolve-artifact-name
        run: |
          echo "artifact_name=artifact-v${{ github.run_number }}.${{ github.run_attempt }}.tar.gz" >> $GITHUB_OUTPUT
      - name: "Resolve artifact path"
        id: resolve-artifact-path
        run: |
          echo "artifact_path=${RUNNER_TEMP}/${{ steps.resolve-artifact-name.outputs.artifact_name }}" >> $GITHUB_OUTPUT
      - name: "Build artifact"
        run: |
          tar --exclude=".git" --exclude=".github" -czf ${{ steps.resolve-artifact-path.outputs.artifact_path }} .
      - name: "Verify artifact"
        run: |
          if [ ! -f ${{ steps.resolve-artifact-path.outputs.artifact_path }} ]; then
            echo "Artifact was not created successfully."
            exit 1
          fi
      - name: "Upload artifact"
        uses: "actions/upload-artifact@v4"
        with:
          name: "${{ steps.resolve-artifact-name.outputs.artifact_name }}"
          if-no-files-found: "error"
          path: "${{ steps.resolve-artifact-path.outputs.artifact_path }}"
